//! Renders `docs/econ-sweep.md` — the candidate table the coordinator reads to
//! propose emission constants in the consensus-parameters appendix.
//!
//! Every number here is a *candidate metric*, not a decision. The report says so,
//! repeatedly and on purpose (the crate's whole discipline).

use crate::checks::all_checks;
use crate::metrics::{Metrics, COMMITTEE_SHARE, MINER_SHARE, TREASURY_SHARE};
use crate::model::Family;
use crate::sweep::{candidates, Candidate};

fn fmt_supply(x: f64) -> String {
    format!("{:.3}M", x / 1e6)
}

/// Group an integer with thousands separators.
fn commas(x: f64) -> String {
    let n = x.round() as i64;
    let s = n.abs().to_string();
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if i > 0 && (s.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    if n < 0 {
        format!("-{out}")
    } else {
        out
    }
}

pub fn render() -> String {
    let cands = candidates();
    let mut s = String::new();

    s.push_str(&preamble());
    s.push_str(&methodology());
    s.push_str(&params_table(&cands));
    s.push_str(&headline_table(&cands));
    s.push_str(&checks_table(&cands));
    s.push_str(&inflation_trajectory_table(&cands));
    s.push_str(&split_flows(&cands));
    s.push_str(&committee_table(&cands));
    s.push_str(&verdict(&cands));
    s.push_str(&how_to_read());
    s.push_str(&reproduce());

    s
}

fn preamble() -> String {
    "\
# Qumbra emission-curve sweep — candidate trade space

> Generated by `qlab-econ` (`cargo run -p qlab-econ --release`). Pure arithmetic;
> no crypto, no chain deps. **Nothing in this document is decided.** Every row is
> a *candidate* emission curve with its trade-offs surfaced, so the coordinator
> can propose constants in the consensus-parameters appendix
> (tokenomics-and-issuance.md §7). This crate chooses no constant.

The design doc fixes the *shape* (§3: smooth closed-form decay into a perpetual
tail; §4: 65/15/20 split) and parks three constants: **initial reward, decay
rate, tail rate**. This sweep evaluates a grid of those three (plus block time,
consensus band 60–75 s) against the §1 four jobs and the §3 calibration
references (Monero landed **0.87 % inflation at tail activation**).

"
    .to_string()
}

fn methodology() -> String {
    format!(
        "\
## Methodology

**Families.** Two closed-form curves, both `{{r0, d, tail}}`-parameterized:

- **Monero-class** — `reward(h) = max(r0·(1−d)^h, tail)`. The §3 precedent: reward
  is a pure function of cumulative issuance (`decay = d·(S_inf − S(h))`, `S_inf =
  r0/d`), decaying geometrically into a **fixed** tail floor — the exact shape
  Todd's asymptotic-non-inflation argument is about. Value-continuous, no cliffs;
  a slope kink at tail activation (C0, like Monero).
- **AdditiveSmooth** — `reward(h) = tail + (r0−tail)·(1−d)^h`. C∞ (no kink), but
  the tail is only *approached*, never a constant emission — so Todd's
  fixed-emission argument holds only in the limit. Included to show the C1 trade.

**Supply-at-height is an exact closed form** (§1 job 4, the audit anchor):

```text
  Monero-class:   S(h) = r0·(1 − (1−d)^h)/d                        for h ≤ h_tail
                       = r0·(1 − (1−d)^h_tail)/d + tail·(h − h_tail) for h > h_tail
  AdditiveSmooth: S(h) = tail·h + (r0−tail)·(1 − (1−d)^h)/d
```

No era table. Anyone evaluates `S(h)` independently and attests Σ(coinbase)
against it (§6). The tests cross-check `S(h)` against the pointwise running
coinbase sum to **< 1 coin** over the full 50-year horizon, and prove the exact
integer telescoping `Σ (S(h+1)−S(h)) = S(h)` in atomic units.

**Split.** {miner:.0} % miners / {committee:.0} % committee / {treasury:.0} %
treasury (§4), applied to every era's emission.

**Committee wage.** 15 % of emission split among N ∈ {{20, 50}} self-bonded
validators (§4b MVI). The wage-vs-subsidy line is ultimately price-dependent
(out of scope) — this sweep surfaces the coin magnitudes and a front-loading
ratio, and flags, rather than deciding.

**Horizon** 50 years; far-future (1000 y) inflation shown to confirm → 0.
**Year** = 365.25 d.

",
        miner = MINER_SHARE * 100.0,
        committee = COMMITTEE_SHARE * 100.0,
        treasury = TREASURY_SHARE * 100.0,
    )
}

fn params_table(cands: &[Candidate]) -> String {
    let mut s = String::from(
        "## 1. Candidate parameters\n\n\
| id | family | block time | half-life | r0 (coin/blk) | tail target | derived d (per-blk) | tail (coin/blk) | S_inf |\n\
|----|--------|-----------:|----------:|--------------:|------------:|--------------------:|----------------:|------:|\n",
    );
    for c in cands {
        let tt = match c.target_tail_infl {
            Some(t) => format!("{:.2}%", t * 100.0),
            None => "— (soft)".to_string(),
        };
        s.push_str(&format!(
            "| {} | {} | {:.0} s | {:.0} y | {:.4} | {} | {:.3e} | {:.5} | {} |\n",
            c.id,
            c.family,
            c.block_time_s,
            c.half_life_years,
            c.r0,
            tt,
            c.model.d,
            c.model.tail,
            fmt_supply(c.model.s_inf()),
        ));
    }
    s.push('\n');
    s
}

fn headline_table(cands: &[Candidate]) -> String {
    let mut s = String::from(
        "## 2. Headline metrics\n\n\
| id | tail activates | infl @ activation | supply @ activation | supply @ 10 y | supply @ 50 y | infl @ 50 y | infl @ 1000 y | curve |\n\
|----|---------------:|------------------:|--------------------:|--------------:|--------------:|------------:|--------------:|:-----:|\n",
    );
    for c in cands {
        let m = Metrics::compute(&c.model);
        let curve = if matches!(c.model.family, Family::AdditiveSmooth) {
            "C∞"
        } else {
            "C0"
        };
        s.push_str(&format!(
            "| {} | y{:.1} ({}) | {:.3}% | {} | {} | {} | {:.4}% | {:.4}% | {} |\n",
            c.id,
            m.tail.year,
            commas(m.tail.height),
            m.tail.inflation_at * 100.0,
            fmt_supply(m.tail.supply_at),
            fmt_supply(c.model.supply_at_year(10.0)),
            fmt_supply(m.supply_50y),
            c.model.annual_inflation(50.0) * 100.0,
            c.model.annual_inflation(1000.0) * 100.0,
            curve,
        ));
    }
    s.push_str("\n> Monero cross-reference: 0.87 % inflation at tail activation, ~year 8–10.\n\n");
    s
}

fn checks_table(cands: &[Candidate]) -> String {
    let mut s = String::from(
        "## 3. Four job-satisfaction checks (§1)\n\n\
Each column is an explicit assertion in `checks.rs`. ✅ = pass. The checks have\n\
teeth: the test suite feeds each a pathological curve that makes it fail.\n\n\
| id | inflation→0 | closed-form | committee-funded | no-cliffs | **all four** |\n\
|----|:-----------:|:-----------:|:----------------:|:---------:|:------------:|\n",
    );
    for c in cands {
        let checks = all_checks(&c.model);
        let mark = |b: bool| if b { "✅" } else { "❌" };
        let all = checks.iter().all(|x| x.pass);
        s.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            c.id,
            mark(checks[0].pass),
            mark(checks[1].pass),
            mark(checks[2].pass),
            mark(checks[3].pass),
            if all { "**✅ PASS**" } else { "**❌**" },
        ));
    }
    // Detail lines for the reference candidate.
    if let Some(m5) = cands.iter().find(|c| c.id == "M5") {
        s.push_str("\n<details><summary>check detail for M5 (the Monero-reference row)</summary>\n\n");
        for chk in all_checks(&m5.model) {
            s.push_str(&format!("- **{}** — {}\n", chk.job, chk.detail));
        }
        s.push_str("\n</details>\n\n");
    }
    s
}

fn inflation_trajectory_table(cands: &[Candidate]) -> String {
    let years = [1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100.0];
    let mut s = String::from(
        "## 4. Annual-inflation trajectory (must trend → 0, §3)\n\n\
Annual inflation (%) at the start of each year. Year-1 is enormous by\n\
construction — a fair launch mints its first supply from zero (§5) — then the\n\
curve decays monotonically toward 0.\n\n\
| id | y1 | y2 | y5 | y10 | y20 | y50 | y100 |\n\
|----|---:|---:|---:|----:|----:|----:|-----:|\n",
    );
    for c in cands {
        s.push_str(&format!("| {} ", c.id));
        for &y in &years {
            s.push_str(&format!("| {:.2} ", c.model.annual_inflation(y) * 100.0));
        }
        s.push_str("|\n");
    }
    s.push('\n');
    s
}

fn split_flows(cands: &[Candidate]) -> String {
    let mut s = String::from(
        "## 5. The 65/15/20 split — absolute flows (§4)\n\n\
### 5a. Cumulative flows through year 50 (coins)\n\n\
| id | total emitted | miners (65%) | committee (15%) | treasury (20%) |\n\
|----|--------------:|-------------:|----------------:|---------------:|\n",
    );
    for c in cands {
        let total = c.model.supply_at_year(50.0);
        s.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            c.id,
            fmt_supply(total),
            fmt_supply(total * MINER_SHARE),
            fmt_supply(total * COMMITTEE_SHARE),
            fmt_supply(total * TREASURY_SHARE),
        ));
    }

    // Per-era detail for the reference candidate M5.
    if let Some(m5) = cands.iter().find(|c| c.id == "M5") {
        let m = Metrics::compute(&m5.model);
        s.push_str(&format!(
            "\n### 5b. Per-era flows for {} (Monero-reference: hl=2 y, 0.87%, 60 s, r0=50)\n\n\
The shape is identical for every candidate; only the S_inf scale changes\n\
(see the D1 denomination row). Coins.\n\n\
| era | total | miners | committee | treasury |\n\
|-----|------:|-------:|----------:|---------:|\n",
            m5.id
        ));
        for e in &m.era_flows {
            s.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                e.label,
                fmt_supply(e.total),
                fmt_supply(e.miner),
                fmt_supply(e.committee),
                fmt_supply(e.treasury),
            ));
        }
        s.push_str(&format!(
            "| tail (per yr, steady) | {} | {} | {} | {} |\n",
            commas(m5.model.tail * m5.model.blocks_per_year()),
            commas(m5.model.tail * m5.model.blocks_per_year() * MINER_SHARE),
            commas(m5.model.tail * m5.model.blocks_per_year() * COMMITTEE_SHARE),
            commas(m5.model.tail * m5.model.blocks_per_year() * TREASURY_SHARE),
        ));
    }
    s.push('\n');
    s
}

fn committee_table(cands: &[Candidate]) -> String {
    let mut s = String::from(
        "## 6. Committee wage — Minimum-Viable-Issuance framing (§4b)\n\n\
Committee income = 15 % of emission, split among N validators. The **perpetual\n\
tail wage** is the steady-state number the tail rate sets forever; year-1 is the\n\
launch peak. Front-loading = year-1 wage ÷ perpetual tail wage — higher means the\n\
launch looks more like a subsidy than a wage. **Whether any of these is a wage or\n\
a subsidy is price-dependent and is the coordinator's call, not this crate's.**\n\n\
| id | tail wage /val/yr (N=20) | (N=50) | year-1 wage /val (N=20) | front-loading× | flag |\n\
|----|------------------------:|-------:|------------------------:|---------------:|:----:|\n",
    );
    for c in cands {
        let m = Metrics::compute(&c.model);
        let w20 = &m.committee_wages[0];
        let w50 = &m.committee_wages[1];
        let frontload = if w20.per_validator_tail > 0.0 {
            w20.per_validator_year1 / w20.per_validator_tail
        } else {
            f64::INFINITY
        };
        let flag = if frontload > 30.0 { "⚠ subsidy-shaped" } else { "—" };
        s.push_str(&format!(
            "| {} | {} | {} | {} | {:.0}× | {} |\n",
            c.id,
            commas(w20.per_validator_tail),
            commas(w50.per_validator_tail),
            commas(w20.per_validator_year1),
            frontload,
            flag,
        ));
    }
    s.push_str(
        "\n> **Illustrative price sensitivity** (NOT a decision — coins have no\n\
> price here): at a hypothetical \\$1/coin, the M5 tail wage of ~4,800\n\
> coin/val/yr (N=20) is ~\\$4.8k/yr — clearly opex-shaped; at \\$100/coin it is\n\
> ~\\$480k/yr — clearly a subsidy. The coordinator picks constants against a\n\
> realistic price/opex assumption (BNB's ~0.9 % APY and ETH's ~3 % from §4b are\n\
> the yield references, but yield needs a stake figure this crate does not model).\n\n",
    );
    s
}

fn verdict(cands: &[Candidate]) -> String {
    let passing: Vec<&str> = cands
        .iter()
        .filter(|c| all_checks(&c.model).iter().all(|x| x.pass))
        .map(|c| c.id.as_str())
        .collect();
    format!(
        "## 7. Which candidates pass all four job-checks\n\n\
**{} of {} candidates pass all four §1 job-checks:** {}.\n\n\
This is the honest headline: the Monero-class shape satisfies the four jobs *by\n\
construction* — perpetual funding (tail > 0), an exact closed-form audit anchor,\n\
asymptotic non-inflation, and no cliffs all hold for every well-formed candidate.\n\
**The pass/fail table does not pick a winner.** The actual decision lives in the\n\
*quantitative* trade-offs (§§2, 4–6): how fast decay front-loads the committee\n\
wage, when the tail activates, the tail-inflation magnitude, and whether the\n\
extra smoothness of a C∞ curve is worth losing Todd's fixed-emission argument.\n\n",
        passing.len(),
        cands.len(),
        passing.join(", "),
    )
}

fn how_to_read() -> String {
    "\
## 8. How to read this (for the appendix proposal)

- **Half-life is the primary economic knob.** Shorter half-life ⇒ tail activates
  sooner, supply concentrates earlier, and the committee wage is more front-loaded
  (the ⚠ flags in §6 track fast decay). Longer half-life spreads issuance and
  keeps committee comp closer to a steady wage — at the cost of a longer
  high-inflation adolescence.
- **Tail target is the perpetual-inflation floor.** 0.5 % / 0.87 % / 1.5 % move
  the steady-state committee+PoW wage proportionally. 0.87 % is the Monero
  landing; below ~0.5 % the perpetual security+committee budget gets thin, above
  ~1.5 % the \"asymptotic-to-0\" framing weakens.
- **Block time (60 vs 75 s)** barely moves the %-metrics — it changes per-block
  reward and block count inversely, so annual flows and inflation are nearly
  invariant (compare the M vs B rows). It is a latency/security choice, not an
  emission-economics one.
- **r0 is pure denomination.** D1 (r0 = 6.25) reproduces every %-metric and
  timing of M5 (r0 = 50) exactly; only the coin counts scale. Pick r0 for
  human-legible denominations, not economics.
- **Monero-class vs AdditiveSmooth** is the C1-vs-Todd trade: the A-rows are
  genuinely smooth (no kink) but never have a *constant* tail, so the
  \"fixed absolute emission is asymptotically non-inflationary\" argument (§3)
  applies only in the limit. Monero-class keeps that argument at the cost of a
  slope kink at activation (which is not a cliff — §3 line, still audit-clean).

"
    .to_string()
}

fn reproduce() -> String {
    "\
## Reproduce

```
cargo run  -p qlab-econ --release          # regenerate this file
cargo test -p qlab-econ --release          # exactness + all four checks + teeth
```
"
    .to_string()
}
