#!/usr/bin/env python3
"""Does the newest PUBLISHED node still speak the same RPC version as the LIVE net?

Lab #614. The release lane is `workflow_dispatch`-only on purpose (see
`release-binaries.yml`'s header: a 10x-billed macOS leg against a $20/month cap
with `Stop usage: Yes`, so an expensive cut can take the acceptance bar down with
it). That cost is known and accepted. What was NOT watched is its consequence:
on 2026-08-22 the published binaries were at `RPC_VERSION = 0x06` while the live
fleet had moved to `0x07`, so anyone following the mining panel's own install
instructions downloaded a node their freshly-built app could not read. Nothing
detected it; it was found by hand while chasing an unrelated bug.

The distinction this exists to make, and the reason a "days since release" metric
would NOT do:

    A release lagging three commits that never touch the wire is fine forever.
    A release lagging ONE commit that bumps RPC_VERSION is broken the moment the
    fleet rolls. "Old" and "incompatible" look identical from the outside and
    only one of them is urgent.

Three readings, taken independently:

  main       the constant in this checkout -- what every freshly built client speaks
  published  the constant at the source revision of the newest release on the
             PUBLIC repo -- what a person who follows our instructions downloads
  live       the first byte of `/v1/anchors` on the public net -- what a remote
             endpoint answers with

FAIL condition is `published != live`: those are the two things a stranger can
end up holding at the same time. `main != live` is reported as a PENDING ROLL
rather than a failure -- it is the normal state between a merge and a deploy.

Every reading fails LOUDLY and distinctly. There is no path here where "could not
measure" is reported as "no skew" -- that inversion is the failure this whole
class of check exists to avoid, and this project has paid for it before (a guard
that compared the string "speed" against 0.00 and could never fire).
"""
import json
import re
import subprocess
import sys

PUBLIC_REPO = "qumbra-labs/qumbra"
LIVE_HOST = "https://seed.qumbra.org"
RPC_CONST_PATH = "crates/qlab-node/src/rpc.rs"
RPC_CONST_RE = re.compile(rb"^pub const RPC_VERSION: u8 = (0x[0-9a-fA-F]+);", re.M)
# The exact line `release-notes.sh` writes (its line 60). Anchored on the
# template rather than on the release TITLE, which is prose and may be reworded.
SOURCE_REV_RE = re.compile(r"^- Source revision: `([0-9a-f]{40})`", re.M)


def die(what, why):
    """Abort with a reading that could not be taken. Never a comparison result."""
    print(f"BADPROBE {what}: {why}", file=sys.stderr)
    raise SystemExit(2)


def run(cmd, what):
    p = subprocess.run(cmd, capture_output=True)
    if p.returncode != 0:
        die(what, f"{cmd[0]} exit {p.returncode}: {p.stderr.decode(errors='replace')[:300]}")
    return p.stdout


def rpc_version_in(blob, what):
    """The one RPC_VERSION in a rpc.rs blob. Two matches is as fatal as none."""
    found = RPC_CONST_RE.findall(blob)
    if len(found) != 1:
        die(what, f"expected exactly one `pub const RPC_VERSION` in {RPC_CONST_PATH}, "
                  f"found {len(found)}. The constant moved or was duplicated; this "
                  f"script must be corrected rather than guessed at.")
    return int(found[0], 16)


def version_at_rev(rev, what):
    blob = run(["git", "show", f"{rev}:{RPC_CONST_PATH}"], what)
    return rpc_version_in(blob, what)


def published_rev():
    """The lab revision the newest published release was built from."""
    out = run(["gh", "release", "view", "--repo", PUBLIC_REPO,
               "--json", "tagName,body"], "published release metadata")
    try:
        meta = json.loads(out)
    except json.JSONDecodeError as e:
        die("published release metadata", f"gh returned non-JSON: {e}")
    body = meta.get("body") or ""
    revs = SOURCE_REV_RE.findall(body)
    if len(revs) != 1:
        die("published source revision",
            f"expected exactly one `- Source revision: <40-hex>` line in the release "
            f"notes for {meta.get('tagName')!r}, found {len(revs)}. That line is "
            f"generated by release-notes.sh; if its template changed, change this "
            f"pattern with it. Refusing to fall back to parsing the title.")
    return meta.get("tagName"), revs[0]


def live_version():
    """First byte of /v1/anchors on the public net.

    The public hostname is CDN-fronted, so a non-200 is reported as its own
    failure: a 403 from the edge is the CDN's opinion of the client, NOT evidence
    about the net, and must never be read as "the net is gone".
    """
    out = run(["curl", "-sS", "-m", "25", "-w", "\n%{http_code}",
               f"{LIVE_HOST}/v1/anchors"], "live net")
    body, _, code = out.rpartition(b"\n")
    code = code.decode().strip()
    if code != "200":
        die("live net", f"HTTP {code} from {LIVE_HOST}/v1/anchors. If this is 403 the "
                        f"CDN answered, not the node -- that is not an outage and not "
                        f"a version reading. Body starts {body[:120]!r}")
    if len(body) < 10:
        die("live net", f"/v1/anchors returned {len(body)} bytes; the header alone is "
                        f"10. A short body is a truncated read, not a version.")
    return body[0]


def main():
    main_v = version_at_rev("HEAD", "main")
    tag, rev = published_rev()
    pub_v = version_at_rev(rev, f"published release {tag}")
    live_v = live_version()

    print(f"main       0x{main_v:02x}   (this checkout)")
    print(f"published  0x{pub_v:02x}   ({tag}, lab rev {rev[:7]})")
    print(f"live       0x{live_v:02x}   ({LIVE_HOST})")
    print()

    if main_v != live_v:
        print(f"PENDING ROLL: main is 0x{main_v:02x} and the live net answers "
              f"0x{live_v:02x}. Not a failure -- this is the ordinary state between a "
              f"merge and a deploy. It becomes one if the fleet rolls without a "
              f"release cut.")

    if pub_v != live_v:
        print()
        print(f"SKEW: the newest published node speaks 0x{pub_v:02x}; the live net "
              f"answers 0x{live_v:02x}.")
        print()
        print("A person following the mining panel's own install instructions today "
              "downloads a node that cannot talk to what they are pointed at, and the "
              "failure they see is `BadVersion` -- which reads as our software being "
              "broken rather than as their download being stale.")
        print()
        print("This does NOT cut a release by itself, and must not grow the ability "
              "to: spending the CI budget is Larry's decision, every time "
              "(release-binaries.yml, R3). This is the measurement that should prompt "
              "the decision, not replace it.")
        return 1

    print(f"OK: published and live both speak 0x{pub_v:02x}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
